---
- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Add rsyslog to Apt Repository
  apt_repository: repo='ppa:adiscon/v8-stable'
  sudo: yes

- name: Updat Apt Packages
  apt: name=rsyslog update_cache=yes
  sudo: yes

- name: Install rsyslog-gnutls
  apt: pkg={{ item }} state=latest
  with_items:
    - rsyslog
    - rsyslog-gnutls
  sudo: yes

- name: Download install Script
  get_url: url=https://www.loggly.com/install/configure-linux.sh dest=/tmp/configure-linux.sh

- name: Configure Loggly
  shell: "/bin/bash /tmp/configure-linux.sh -s -a {{ loggly_account_name }} -t {{ loggly_token }} -u {{ loggly_username }} -p '{{ loggly_password }}'"
  sudo: yes
